### ISSUE TITLE
numpy-aipi ImportError: cannot locate symbol "acoshf" referenced by "libgfortran.so"

### ISSUE THREAD

**Issue by OlafHaag** [qpython-android/aipy#1]
I installed QPython 2.0.7 and AIPY, then through QPYPI's GUI interface downloaded numpy from the AIPY tab. Started a terminal and did import numpy. Below is the output. I also tried resetting the storage and install again, I even uninstalled in re-installed QPython and AIPY, but I always got the same error. This is also preventing me from using any other of the AI packages like theano.
> 

Python 2.7.12 (default, Sep 28 2017, 11:17:05) [GCC 4.9.x 20150123 (prerelease)] on linux4 Type "help", "copyright", "credits" or "license" for more information. >>> import numpy Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/__init__.py",  line 142, in <module> from . import add_newdocs File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/add_newdocs.py",  line 13, in <module> from numpy.lib import add_newdoc File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/lib/__init__.py",  line 8, in <module> from .type_check import * File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/lib/type_check.py",  line 11, in <module> import numpy.core.numeric as _nx File "/data/data/org.qpython.qpy/files/lib/python2.7/site-packages/numpy_aipy-1.13.1-py2.7.egg/numpy/core/__init__.py",  line 26, in <module> raise ImportError(msg) ImportError: Importing the multiarray numpy extension module failed. Most likely you are trying to import a failed build of numpy. If you're working with a numpy git repo, try `git clean -xdf` (removes all files not under version control). Otherwise reinstall numpy. Original error was: dlopen failed: could not load library "libopenblas.so" needed by "multiarray.so"; caused by could not load library "libgfortran.so" needed by "libopenblas.so"; caused by cannot locate symbol "acoshf" referenced by "libgfortran.so"...
--

**Comment by riverfor** [comment]
It is not compatible with your mobile, we will fix it as soon.

Thanks for feedback.

**Comment by OlafHaag** [comment]
This was on a Samsung S4 Mini device with Android 4.4.2. I since switched from Samsung's OEM Android to Lineage 14 (Android 7.1) and now numpy is importing correctly!

**Comment by riverfor** [comment]
Good to know that.
