### ISSUE TITLE
I installed qpython first and my aipy still remind me 'install qpython first'

### ISSUE THREAD

**Issue by luohc2004** [qpython-android/aipy#3]
my os is MIUI9.1.4.0 Android7.0. qpython version is Qpython3 (1.0.3)

**Comment by riverfor** [comment]
Sorry, it doesn't support QPython3 yet.
Please try it with QPython  ( Newest https://github.com/qpython-android/qpython/releases/tag/v2.1.1 )

**Comment by riverfor** [comment]
We will add qpython3 support as soon.
